from enum import Enum

SPEED = 30 # 30 - default, 0 - max speed
PLAY_SOUNDS = False
SHOW_SCREEN = True
FREEZ_AT_THE_END = False

FLAP = True
NOT_FLAP = False

HORIZONTAL_VELOCITY = 4
FLAP_VELOCITY = -9
MAX_VELOCITY = 10

GAP_SIZE = 100
IMAGES_PLAYER_HEIGHT = 24

PIPE_WIDTH = 52
BIRD_WIDTH = 34
BIRD_HEIGHT = 24
VERTICAL_GAP_SIZE = 100

INFINITE_GAMES = -1
